FROM mysql:5.6

# Debian's /bin/sh doesn't support `set -o pipefail`.
SHELL ["/bin/bash", "-c"]

COPY mysql /etc/mysql/mysql.conf.d

RUN set -ex -o pipefail; \
    mkdir -p /usr/local/sbin; \
    mkdir -p /usr/local/lib/site_perl; \
    build_pkgs="ca-certificates curl"; \
    apt update; \
    apt install -y --no-install-recommends $build_pkgs; \
    ### dockerize
    DOCKERIZE_VER="0.10.0"; \
    curl -sfL https://github.com/powerman/dockerize/releases/download/v$DOCKERIZE_VER/dockerize-`uname -s`-`uname -m` | install /dev/stdin /usr/local/bin/dockerize; \
    ### init DB
    MYSQL_ALLOW_EMPTY_PASSWORD=yes docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci & \
    dockerize -wait tcp://127.0.0.1:3306; \
    pid="$(cat /var/run/mysqld/mysqld.pid)"; \
    kill -s TERM "$pid"; \
    wait "$pid"; \
    tar czf /var/lib/mysql.tgz -C /var/lib mysql; \
    ### Cleanup
    apt autoremove -y $build_pkgs; \
    rm -rf /var/lib/apt/lists/* /tmp/*

ENTRYPOINT ["bash", "-c", " \
    test -d /var/lib/mysql/mysql || tar xzpf /var/lib/mysql.tgz -C /var/lib; \
    exec docker-entrypoint.sh \"$0\" \"$@\" \
    "]
CMD ["mysqld"]

# No needs to upgrade, add this just to reuse default CI build task.
ARG UPGRADE
RUN echo $UPGRADE > /var/cache/UPGRADE
