#!/bin/sh
mode=$1
file=$2
shift 2
# getfattr here is mostly to avoid `sync` when it's not needed
if test "$mode" != "$(getfattr -n user.pax.flags --only-values "$file" 2>/dev/null)"; then
        setfattr -n user.pax.flags -v "$mode" "$file"
        sync # without this on CircleCI "text file busy" happens on exec
fi
exec "$file" "$@"
