default-job: &default-job
        docker:
            - image: docker:17.06.2-ce-git
        steps:
            - checkout
            - setup_remote_docker
            # TODO Avoid rebuild if nothing changes (Dockerfile, OS
            # updates, installed dependencies). Implement in general way:
            # `docker run -t cpdpro/baseimage:$CIRCLE_JOB check.$CIRCLE_JOB`
            - restore_cache:
                key: "v1:{{ .Environment.CIRCLE_JOB }}:{{ checksum \"Dockerfile.{{ .Environment.CIRCLE_JOB }}\" }}"
                keys:
                    - "v1:{{ .Environment.CIRCLE_JOB }}:"
            - run:
                name: Load docker image layer cache
                command: |
                    ls -l /var/cache/
                    docker load -i /var/cache/$CIRCLE_JOB.tar || true
            - run:
                name: docker build
                command: |
                    docker build \
                        --build-arg UPGRADE=$(date -Ihours) \
                        --cache-from cpdpro/baseimage:$CIRCLE_JOB \
                        -t cpdpro/baseimage:$CIRCLE_JOB \
                        -f Dockerfile.$CIRCLE_JOB \
                        .
                    if test "$CIRCLE_BUILD_NUM"; then # empty on local circleci
                        docker tag \
                            cpdpro/baseimage:$CIRCLE_JOB \
                            cpdpro/baseimage:$CIRCLE_JOB.$CIRCLE_BUILD_NUM
                    fi
            - run:
                name: Save docker image layer cache
                command: |
                    docker save -o /var/cache/$CIRCLE_JOB.tar cpdpro/baseimage:$CIRCLE_JOB || true
            - save_cache:
                key: "v1:{{ .Environment.CIRCLE_JOB }}:{{ checksum \"Dockerfile.{{ .Environment.CIRCLE_JOB }}\" }}"
                paths:
                    - /var/cache/$CIRCLE_JOB.tar
            - deploy:
                name: docker push
                command: |
                    if test "$CIRCLE_BRANCH" = "master" && test "$DOCKER_USER"; then
                        docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
                        docker push cpdpro/baseimage:$CIRCLE_JOB
                        if test "$CIRCLE_BUILD_NUM"; then # empty on local circleci
                            docker push cpdpro/baseimage:$CIRCLE_JOB.$CIRCLE_BUILD_NUM
                        fi
                    fi

version: 2
jobs:
    base-narada4d:
        <<: *default-job
    build-golang:
        <<: *default-job
workflows:
    version: 2
    all:
        jobs:
            - base-narada4d
            - build-golang
